version: '3'

services:
  otusdb:
    image: mysql:8.0.15
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    command:
      --init-file /init.sql
    volumes:
      - ./init.sql:/init.sql
      - ./custom.conf:/etc/mysql/conf.d
      - ./some_data.csv:/some_data.csv
    expose:
      - "3306"
    ports:
      - "3309:3306"