CREATE database TRADEBASE;
CREATE USER 'TRADEBASE_USER'@'%' IDENTIFIED WITH caching_sha2_password BY '12345';
GRANT ALL PRIVILEGES ON TRADEBASE.* TO 'TRADEBASE_USER'@'%';
USE TRADEBASE;

CREATE TABLE STATUSES
(
    ID binary(16) PRIMARY KEY,
    TYPE VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE LOT_TYPES
(
    ID binary(16) PRIMARY KEY,
    PARENT_ID binary(16),
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE EVENT_TYPES
(
    ID binary(16) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE EVENT_CATEGORIES
(
    ID binary(16) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE CURRENCIES
(
    ID binary(16) PRIMARY KEY,
    CODE VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE PERSONS
(
    ID binary(16) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    SURNAME VARCHAR(255) NOT NULL,
    PATRONYMIC VARCHAR(255) NOT NULL,
    MAIL VARCHAR(255) NOT NULL,
    PHONENUMBER VARCHAR(255) NOT NULL,
    PERSON_STATUS_ID binary(16),
	FOREIGN KEY (PERSON_STATUS_ID)
        REFERENCES STATUSES(id)
);

CREATE TABLE EVENTS
(
    ID binary(16) PRIMARY KEY,
    DESCRIPTION VARCHAR(255) NOT NULL,
    EVENT_STATUS_ID binary(16),
    EVENT_TYPE_ID binary(16),
    START_DATE DATE,
    END_DATE DATE,
    PRICE INT,
    CURRENCY_ID binary(16),
    PERSON_ID binary(16),
	FOREIGN KEY (EVENT_STATUS_ID)
        REFERENCES STATUSES(id),
	FOREIGN KEY (EVENT_TYPE_ID)
        REFERENCES EVENT_TYPES(id),
	FOREIGN KEY (CURRENCY_ID)
        REFERENCES CURRENCIES(id),
	FOREIGN KEY (PERSON_ID)
        REFERENCES PERSONS(id)
);

CREATE TABLE LOTS
(
    ID binary(16) PRIMARY KEY,
    DESCRIPTION VARCHAR(255) NOT NULL,
    LOT_TYPE_ID binary(16),
    OWNER_ID binary(16),
    LOT_STATUS_ID binary(16),
	FOREIGN KEY (LOT_TYPE_ID)
        REFERENCES LOT_TYPES(id),
	FOREIGN KEY (OWNER_ID)
        REFERENCES PERSONS(id),
	FOREIGN KEY (LOT_STATUS_ID)
        REFERENCES STATUSES(id)
);

CREATE TABLE LOT_TO_EVENT
(
    ID binary(16) PRIMARY KEY,
    LOT_ID binary(16),
    EVENT_ID binary(16),
	FOREIGN KEY (LOT_ID)
        REFERENCES LOTS(id),
	FOREIGN KEY (EVENT_ID)
        REFERENCES EVENTS(id)
);

CREATE TABLE CATEGORY_TO_EVENT
(
    ID binary(16) PRIMARY KEY,
    EVENT_CATEGORY_ID binary(16),
    EVENT_ID binary(16),
	FOREIGN KEY (EVENT_CATEGORY_ID)
        REFERENCES EVENT_CATEGORIES(id),
	FOREIGN KEY (EVENT_ID)
        REFERENCES EVENTS(id)
);

CREATE TABLE ORDERS
(
    ID binary(16) PRIMARY KEY,
    PERSON_ID binary(16),
    ORDER_STATUS_ID binary(16),
    PRICE INT,
    CURRENCY_ID binary(16),
    EVENT_ID binary(16),
    ORDER_DATE TIMESTAMP,
	FOREIGN KEY (PERSON_ID)
        REFERENCES PERSONS(id),
	FOREIGN KEY (ORDER_STATUS_ID)
        REFERENCES STATUSES(id),
	FOREIGN KEY (CURRENCY_ID)
        REFERENCES CURRENCIES(id),
	FOREIGN KEY (EVENT_ID)
        REFERENCES EVENTS(id)
);