CREATE DATABASE TRADEBASE;
CREATE USER TRADEBASE_USER WITH ENCRYPTED PASSWORD 'MYPASS';
GRANT ALL PRIVILEGES ON DATABASE TRADEBASE TO TRADEBASE_USER;
\C TRADEBASE TRADEBASE_USER;
CREATE SCHEMA AUCTION;

CREATE TABLE AUCTION.STATUSES
(
    ID UUID,
    TYPE VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    CONSTRAINT STATUSES_PK PRIMARY KEY (ID)
);

CREATE TABLE AUCTION.LOT_TYPES
(
    ID UUID,
    PARENT_ID UUID,
    NAME VARCHAR(255) NOT NULL,
    CONSTRAINT LOT_TYPES_PK PRIMARY KEY (ID)
);

CREATE TABLE AUCTION.EVENT_TYPES
(
    ID UUID,
    NAME VARCHAR(255) NOT NULL,
    CONSTRAINT EVENT_TYPES_PK PRIMARY KEY (ID)
);

CREATE TABLE AUCTION.EVENT_CATEGORIES
(
    ID UUID,
    NAME VARCHAR(255) NOT NULL,
    CONSTRAINT EVENT_CATEGORIES_PK PRIMARY KEY (ID)
);

CREATE TABLE AUCTION.CURRENCIES
(
    ID UUID,
    CODE VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    CONSTRAINT CURRENCIES_PK PRIMARY KEY (ID)
);

CREATE TABLE AUCTION.PERSONS
(
    ID UUID,
    NAME VARCHAR(255) NOT NULL,
    SURNAME VARCHAR(255) NOT NULL,
    PATRONYMIC VARCHAR(255) NOT NULL,
    MAIL VARCHAR(255) NOT NULL,
    PHONENUMBER INT NOT NULL,
    PERSON_STATUS_ID UUID,
    CONSTRAINT PERSONS_PK PRIMARY KEY (ID),
    CONSTRAINT FK_PERSON_STATUS_ID FOREIGN KEY (PERSON_STATUS_ID) REFERENCES AUCTION.STATUSES(ID)
);

CREATE TABLE AUCTION.EVENTS
(
    ID UUID,
    DESCRIPTION VARCHAR(255) NOT NULL,
    EVENT_STATUS_ID UUID,
    EVENT_TYPE_ID UUID,
    START_DATE DATE,
    END_DATE DATE,
    PRICE INT,
    CURRENCY_ID UUID,
    PERSON_ID UUID,
    CONSTRAINT EVENTS_PK PRIMARY KEY (ID),
    CONSTRAINT FK_EVENT_STATUS_ID FOREIGN KEY (EVENT_STATUS_ID) REFERENCES AUCTION.STATUSES(ID),
    CONSTRAINT FK_EVENT_TYPE_ID FOREIGN KEY (EVENT_TYPE_ID) REFERENCES AUCTION.EVENT_TYPES(ID),
    CONSTRAINT FK_CURRENCY_ID FOREIGN KEY (CURRENCY_ID) REFERENCES AUCTION.CURRENCIES(ID),
    CONSTRAINT FK_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES AUCTION.PERSONS(ID)
);

CREATE TABLE AUCTION.LOTS
(
    ID UUID,
    DESCRIPTION VARCHAR(255) NOT NULL,
    LOT_TYPE_ID UUID,
    OWNER_ID UUID,
    LOT_STATUS_ID UUID,
    CONSTRAINT LOTS_PK PRIMARY KEY (ID),
    CONSTRAINT FK_LOT_TYPE_ID FOREIGN KEY (LOT_TYPE_ID) REFERENCES AUCTION.LOT_TYPES(ID),
    CONSTRAINT FK_OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES AUCTION.PERSONS(ID),
    CONSTRAINT FK_LOT_STATUS_ID FOREIGN KEY (LOT_STATUS_ID) REFERENCES AUCTION.STATUSES(ID)
);

CREATE TABLE AUCTION.LOT_TO_EVENT
(
    ID UUID,
    LOT_ID UUID,
    EVENT_ID UUID,
    CONSTRAINT LOT_TO_EVENT_PK PRIMARY KEY (ID),
    CONSTRAINT FK_LOT_ID FOREIGN KEY (LOT_ID) REFERENCES AUCTION.LOTS(ID),
    CONSTRAINT FK_EVENT_ID FOREIGN KEY (EVENT_ID) REFERENCES AUCTION.EVENTS(ID)
);

CREATE TABLE AUCTION.CATEGORY_TO_EVENT
(
    ID UUID,
    EVENT_CATEGORY_ID UUID,
    EVENT_ID UUID,
    CONSTRAINT CATEGORY_TO_EVENT_PK PRIMARY KEY (ID),
    CONSTRAINT FK_EVENT_CATEGORY_ID FOREIGN KEY (EVENT_CATEGORY_ID) REFERENCES AUCTION.EVENT_CATEGORIES(ID),
    CONSTRAINT FK_EVENT_ID FOREIGN KEY (EVENT_ID) REFERENCES AUCTION.EVENTS(ID)
);

CREATE TABLE AUCTION.ORDERS
(
    ID UUID,
    PERSON_ID UUID,
    ORDER_STATUS_ID UUID,
    PRICE INT,
    CURRENCY_ID UUID,
    EVENT_ID UUID,
    ORDER_DATE DATE,
    CONSTRAINT ORDERS_PK PRIMARY KEY (ID),
    CONSTRAINT FK_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES AUCTION.PERSONS(ID),
    CONSTRAINT FK_ORDER_STATUS_ID FOREIGN KEY (ORDER_STATUS_ID) REFERENCES AUCTION.STATUSES(ID),
    CONSTRAINT FK_CURRENCY_ID FOREIGN KEY (CURRENCY_ID) REFERENCES AUCTION.CURRENCIES(ID),
    CONSTRAINT FK_EVENT_ID FOREIGN KEY (EVENT_ID) REFERENCES AUCTION.EVENTS(ID)
);
